In [2]:
import numpy as np

In [4]:
a1 = np.random.randint(0,5,size=(3,5))
a1

array([[0, 1, 3, 2, 2],
       [2, 3, 2, 1, 2],
       [2, 2, 2, 1, 3]])

In [6]:
a1*2#乘2代表所有数都乘以2

array([[0, 2, 6, 4, 4],
       [4, 6, 4, 2, 4],
       [4, 4, 4, 2, 6]])

In [8]:
a2 = np.random.randint(0,5,size =(3,5))
a2

array([[1, 2, 3, 1, 1],
       [2, 0, 0, 1, 4],
       [0, 0, 1, 3, 0]])

In [10]:
a1 + a2#行列数不一样的数组不能相加

array([[1, 3, 6, 3, 3],
       [4, 3, 2, 2, 6],
       [2, 2, 3, 4, 3]])

# 数组与数组之间的计算

In [15]:
a3 = np.random.randint(0,5,size=(3,1))
a3

array([[3],
       [0],
       [2]])

In [17]:
a1+a3#行列数不一样的数组不能相加,但若有一个数组列为1例外，此含义为大的数组每一列都要去加上小的数组

array([[3, 4, 6, 5, 5],
       [2, 3, 2, 1, 2],
       [4, 4, 4, 3, 5]])

In [20]:
a4 = np.random.randint(0,5,size=(1,5))
a4

array([[2, 4, 0, 2, 2]])

In [23]:
a1+a4#对于行同理

array([[2, 5, 3, 4, 4],
       [4, 7, 2, 3, 4],
       [4, 6, 2, 3, 5]])

广播机制：两个数组的后缘维度的轴长度相符或者其中一方长度为1，则认为他们是广播相容的，广播会在缺失和长度为1的维度上进行。