In [1]:
import numpy as np

# reshape和resize

In [6]:
a1 = np.random.randint(0,5,size=(3,4))
a1

array([[3, 1, 0, 0],
       [1, 3, 0, 4],
       [1, 1, 0, 0]])

In [8]:
a1.reshape((2,6))

array([[3, 1, 0, 0, 1, 3],
       [0, 4, 1, 1, 0, 0]])

In [10]:
a1#reshape并回去修改数组本身


array([[3, 1, 0, 0],
       [1, 3, 0, 4],
       [1, 1, 0, 0]])

In [13]:
a1.resize((2,6))
a1#resize会修改数组的形状

array([[3, 1, 0, 0, 1, 3],
       [0, 4, 1, 1, 0, 0]])


# flatten和ravel方法

In [16]:
a1.flatten()

array([3, 1, 0, 0, 1, 3, 0, 4, 1, 1, 0, 0])

In [18]:
a1

array([[3, 1, 0, 0, 1, 3],
       [0, 4, 1, 1, 0, 0]])

In [20]:
a1.ravel()

array([3, 1, 0, 0, 1, 3, 0, 4, 1, 1, 0, 0])

In [22]:
a1

array([[3, 1, 0, 0, 1, 3],
       [0, 4, 1, 1, 0, 0]])

flatten和ravel都不会对数组产生影响

但是flatten返回的是一个拷贝，而ravel返回的事一个引用，也就是说，对返回的数组进行赋值的时候，会出现结果的不同

In [26]:
a1


array([[3, 1, 0, 0, 1, 3],
       [0, 4, 1, 1, 0, 0]])

In [34]:
a2 = a1.flatten()
a2[0]=10
a2

array([10,  1,  0,  0,  1,  3,  0,  4,  1,  1,  0,  0])

In [36]:
a1

array([[3, 1, 0, 0, 1, 3],
       [0, 4, 1, 1, 0, 0]])

In [39]:
a3 = a1.ravel()
a3[0]=11
a3


array([11,  1,  0,  0,  1,  3,  0,  4,  1,  1,  0,  0])

In [40]:
a1

array([[11,  1,  0,  0,  1,  3],
       [ 0,  4,  1,  1,  0,  0]])