# 垂直，水平叠加

In [2]:
import numpy as np

In [4]:
#垂直叠加，列数必须相同
a1 = np.random.randint(0,10,(3,4))
a2 = np.random.randint(0,10,(2,4))#两数组行数不相同，但列数相同
#垂直叠加
a3 = np.vstack([a1,a2])
a3

array([[7, 2, 5, 8],
       [3, 0, 9, 0],
       [1, 0, 6, 0],
       [8, 5, 3, 2],
       [3, 4, 8, 7]])

In [7]:
#水平叠加，行数一致
a4 = np.random.randint(0,10,(3,4))
a5 = np.random.randint(0,10,(3,7))

a6 = np.hstack([a4,a5])
a6

array([[3, 1, 6, 1, 0, 3, 3, 1, 5, 2, 5],
       [6, 2, 5, 2, 3, 6, 2, 0, 6, 2, 4],
       [6, 7, 8, 4, 2, 8, 9, 2, 4, 3, 8]])

In [9]:
#一个通用的函数，需要指定在哪个轴上叠加axis=0位纵轴叠加（垂直）
a7 =np.concatenate([a1,a2],axis=0)
a8 =np.concatenate([a4,a5],axis=1)
a8

array([[3, 1, 6, 1, 0, 3, 3, 1, 5, 2, 5],
       [6, 2, 5, 2, 3, 6, 2, 0, 6, 2, 4],
       [6, 7, 8, 4, 2, 8, 9, 2, 4, 3, 8]])