In [2]:
import numpy as np

In [9]:
a1 = np.random.randint(0,10,size=[3,4])
a1

array([[4, 0, 5, 0],
       [9, 9, 6, 1],
       [9, 0, 5, 9]])

In [ ]:
#hsplit纵向切割

In [7]:
np.hsplit(a1,2)#平均分成两份，列数必须可以被2整除

[array([[7, 3],
        [6, 5],
        [8, 2]]),
 array([[6, 3],
        [6, 8],
        [0, 2]])]

In [8]:
#指定切割的位置,可以指定多个位置
np.hsplit(a1,(1,2))#对a1数组的第一列和第二列进行切割



[array([[7],
        [6],
        [8]]),
 array([[3],
        [5],
        [2]]),
 array([[6, 3],
        [6, 8],
        [0, 2]])]

In [11]:
#横向切割
np.vsplit(a1,(1,2))

[array([[4, 0, 5, 0]]), array([[9, 9, 6, 1]]), array([[9, 0, 5, 9]])]

In [13]:
np.vsplit(a1,3)

[array([[4, 0, 5, 0]]), array([[9, 9, 6, 1]]), array([[9, 0, 5, 9]])]

In [15]:
#综合型,axis=0位横向切割，=1为纵向切割
np.split(a1,(1,2),axis=0)

[array([[4, 0, 5, 0]]), array([[9, 9, 6, 1]]), array([[9, 0, 5, 9]])]