In [2]:
import numpy as np

In [20]:
a1 = np.random.randint(0,10,(3,4))
a1

array([[3, 6, 6, 0],
       [4, 3, 6, 9],
       [3, 4, 7, 1]])

In [21]:
a1.T
a2 =a1.T

In [22]:
#矩阵相乘
a1.dot(a1.T)

array([[ 81,  66,  75],
       [ 66, 142,  75],
       [ 75,  75,  75]])

In [23]:
a1.transpose()#transpose()转置矩阵返回的是一View

array([[3, 4, 3],
       [6, 3, 4],
       [6, 6, 7],
       [0, 9, 1]])