In [2]:
import numpy as np

In [18]:
a1 = np.random.randint(0,10,(3,6))
a1

array([[5, 8, 0, 2, 6, 0],
       [3, 5, 4, 9, 9, 7],
       [8, 4, 5, 2, 3, 0]])

In [19]:
print(a1<6)#可以看出a1数组里小于6的都标记为true#判断条件多样，不仅只有这个；也可以多条件

[[ True False  True  True False  True]
 [ True  True  True False False False]
 [False  True  True  True  True  True]]


In [20]:
a1[a1<6]

array([5, 0, 2, 0, 3, 5, 4, 4, 5, 2, 3, 0])

In [22]:
a1[(a1<6) & (a1>2)]#多条件

array([5, 3, 5, 4, 4, 5, 3])