In [15]:
import numpy as np

## 1.数据类型统一

In [13]:

b = [1,2,'3','4']#在python里数组内数据类型可以是任意的，但在nparray里数据类型需要是统一的


In [14]:
a= np.array(b)
a#如下所示，b列表里所有数据都被转换成了字符型

array(['1', '2', '3', '4'], dtype='<U21')

## 2.数组创建

In [23]:
#1.使用np.array创建数组

a =np.array([1,2,3,4])
print(a)#打印数组中间是没有逗号的，和列表区分
print(type(a))

[1 2 3 4]
<class 'numpy.ndarray'>


In [25]:
#2.使用np.arange创建数组

b = np.arange(10)#会返回一个0-10数组
b

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [31]:
#3.使用random生成随机数

c = np.random.random((2,2))#给出你希望得到一个几行几列的数组
c


array([[0.52401952, 0.03271492],
       [0.32464585, 0.91601857]])

In [33]:
d = np.random.randint(0,9,size=(4,4))#这里表示需要一个包含0-9整型2*2数组
d

array([[1, 2, 2, 8],
       [1, 7, 7, 1],
       [4, 8, 0, 8],
       [3, 5, 6, 2]])

In [43]:
#4.特殊函数
a1 = np.zeros((3,3))
a2 = np.ones((4,4))
a3 = np.full((5,5),666)#创建一个5行5列的数组，填入666
a4 =np.eye(4)#在对角线上填入4
a4

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

# 总结：
#1.使用np.array创建数组    
#2.使用np.arange创建数组    
#3.使用random生成随机数    
#4.特殊函数      
nparray里数据类型需要是统一的  