In [2]:
import numpy as np

In [4]:
a1 = np.random.randint(0,10,(4,6))
a1

array([[5, 3, 6, 6, 7, 4],
       [9, 9, 8, 7, 1, 1],
       [5, 5, 6, 6, 1, 3],
       [1, 4, 4, 2, 4, 9]])

In [8]:
#数组某一个部位值的替换，首先用索引找到对应的部位，在将准备好的值赋予

a1[1] =np.arange(6)
a1

array([[5, 3, 6, 6, 7, 4],
       [0, 1, 2, 3, 4, 5],
       [5, 5, 6, 6, 1, 3],
       [1, 4, 4, 2, 4, 9]])

In [13]:
np.where(a1<5)#下面给的两行指的是位置

(array([0, 0, 1, 1, 1, 1, 1, 2, 2, 3, 3, 3, 3, 3]),
 array([1, 5, 0, 1, 2, 3, 4, 4, 5, 0, 1, 2, 3, 4]))

In [16]:
a1[a1<5]=4

In [17]:
np.where(a1<5,0,1)#如果满足条件，就替换成0，反之变为1

array([[1, 0, 1, 1, 1, 0],
       [0, 0, 0, 0, 0, 1],
       [1, 1, 1, 1, 0, 0],
       [0, 0, 0, 0, 0, 1]])